# Order Eureka Discovery Server (Service)

# Start the Eureka Server with appropriate Profile
# java -jar -Dspring.profiles.active=P1 DiscoveryService.war

# Default Server Configuration
server:
  port: 9020
  servlet:
    context-path: /
    
# Discovery
eureka:
  instance:
    appname: DiscoveryService
    prefer-ip-address: false
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    region: default
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
  server:
    enable-self-preservation: true

# Actuator
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator/
      exposure:
        include: '*'

---
# Profile 'dev'
spring:
  profiles: dev
  
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:9020/eureka/
  
# Logging
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
    com:
      sales:
        order: DEBUG